--
-- Script was generated by Devart dbForge Studio 2020 for PostgreSQL, Version 2.3.230.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 10.08.2021 11:59:25
-- Server version: PostgreSQL 13.1
--


INSERT INTO vue_spa.public.users(id, name, email, email_verified_at, password, remember_token, is_admin, created_at, updated_at) VALUES
(1, E'Михаил Тукшов', E'man24@yandex.ru', null, E'$2y$10$Qm2a3miAEnuxPGHYm3C/Eu84xMGpXsSpaue2ltwIXzvScKDT6GDuK', null, 0, '09.08.2021 5:51:46.000000 AD', '09.08.2021 5:55:04.000000 AD');
INSERT INTO vue_spa.public.users(id, name, email, email_verified_at, password, remember_token, is_admin, created_at, updated_at) VALUES
(2, E'Брагин Антон', E'man25@yandex.ru', null, E'$2y$10$m3Zitfc7cWXPbaJp3c486uUa6.H/EIJgrFxYJprubbg5Tcb5bAdFS', null, 1, '09.08.2021 6:08:53.000000 AD', '09.08.2021 6:08:53.000000 AD');