# Для начала указываем исходный образ, он будет использован как основа
FROM php:7.4-fpm
# Необязательная строка с указанием автора образа
MAINTAINER andreechka <man24@yandex.ru>

# RUN выполняет идущую за ней команду в контексте нашего образа.
# В данном случае мы установим некоторые зависимости и модули PHP.
# Для установки модулей используем команду docker-php-ext-install.
# На каждый RUN создается новый слой в образе, поэтому рекомендуется объединять команды.
RUN apt-get update && apt-get install -y \
	software-properties-common \
	npm \
        curl \
        wget \
        git \
	libonig-dev \
	libxml2-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
	libpq-dev \
	libzip-dev \
        zlib1g-dev \
        zip \
    && docker-php-ext-install -j$(nproc) bcmath ctype fileinfo json tokenizer xml mbstring pdo pdo_pgsql zip

RUN npm install npm@lts -g && \
    npm install n -g && \
    n latest    

# Куда же без composer'а.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get install -y \
	postgresql-client

# Добавим свой php.ini, можем в нем определять свои значения конфига
#ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini

# Указываем рабочую директорию для PHP
WORKDIR /var/www

#RUN php artisan migrate:refresh

#ADD init-db.sh /tmp

# Запускаем контейнер
# Из документации: The main purpose of a CMD is to provide defaults for an executing container. These defaults can include an executable, 
# or they can omit the executable, in which case you must specify an ENTRYPOINT instruction as well.
CMD ["php-fpm"]



#COPY ./entrypoint.sh /usr/bin/entrypoint.sh


#ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]


